### PR TITLE
fix: loosen pin on bluetooth-data-tools

### PR DESCRIPTION
**Pull request by bdraco**
needed to fix https://github.com/home-assistant/core/pull/91442

### CODE REVIEW

**Comment by bdraco** [comment]
@akx Can you take a look? This is blocking some other changes on core

**Review by akx — APPROVED** [review]

**Comment by akx** [comment]
@bdraco Published in https://pypi.org/project/aioruuvigateway/0.1.0/ :)

**Comment by bdraco** [comment]
Thanks. Do you want to bump it in Home Assistant, or should I take care of it?

**Comment by akx** [comment]
> Thanks. Do you want to bump it in Home Assistant, or should I take care of it?

Feel free to 👍

**Pull request merged**
